-- Supabase schema for The Beach Project Restobar Ops.
-- Paste this file into the Supabase SQL Editor, or run it with the Supabase CLI.

begin;

do $$
begin
  create type public.staff_role as enum ('Admin', 'Staff', 'Kitchen');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.staff_status as enum ('Active', 'Inactive');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.table_status as enum ('Available', 'Occupied', 'For Cleaning');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.prep_station as enum ('Kitchen', 'Bar');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.order_status as enum (
    'Awaiting Payment',
    'Paid',
    'Preparing',
    'Ready',
    'Served',
    'Cancelled',
    'Refunded'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.payment_status as enum ('Pending', 'Paid', 'Failed', 'Refunded');
exception
  when duplicate_object then null;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.staff_accounts (
  id text primary key,
  name text not null check (length(trim(name)) > 0),
  username text not null unique check (username = lower(username)),
  password text not null check (length(password) > 0),
  role public.staff_role not null default 'Staff',
  status public.staff_status not null default 'Active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.staff_accounts.password is
  'Temporary demo-login password field. Replace with Supabase Auth or password hashes before production.';

create table if not exists public.tables (
  id text primary key,
  name text not null check (length(trim(name)) > 0),
  area text not null check (length(trim(area)) > 0),
  capacity integer not null check (capacity > 0),
  status public.table_status not null default 'Available',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.table_sessions (
  id text primary key,
  table_id text not null references public.tables(id) on update cascade on delete restrict,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (closed_at is null or closed_at >= opened_at)
);

create table if not exists public.menu_items (
  id text primary key,
  name text not null check (length(trim(name)) > 0),
  category text not null check (length(trim(category)) > 0),
  price_cents integer not null check (price_cents >= 0),
  station public.prep_station not null,
  available boolean not null default true,
  stock_qty integer not null default 0 check (stock_qty >= 0),
  archived boolean not null default false,
  tone text not null default 'sunset',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  session_id text not null references public.table_sessions(id) on update cascade on delete restrict,
  table_id text not null references public.tables(id) on update cascade on delete restrict,
  status public.order_status not null default 'Awaiting Payment',
  payment_status public.payment_status not null default 'Pending',
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  paid_by text,
  staff text not null,
  customer_name text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on update cascade on delete cascade,
  line_id text not null,
  menu_item_id text not null references public.menu_items(id) on update cascade on delete restrict,
  name text not null,
  category text not null,
  station public.prep_station not null,
  quantity integer not null check (quantity > 0),
  price_cents integer not null check (price_cents >= 0),
  instructions text not null default '',
  created_at timestamptz not null default now(),
  unique (order_id, line_id)
);

create table if not exists public.payments (
  id text primary key,
  order_id text not null references public.orders(id) on update cascade on delete restrict,
  method text not null default 'Cash',
  status public.payment_status not null default 'Paid',
  amount_cents integer not null check (amount_cents >= 0),
  amount_received_cents integer not null check (amount_received_cents >= amount_cents),
  change_cents integer not null check (change_cents >= 0),
  customer_name text not null,
  staff text not null,
  paid_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id text primary key,
  category text not null check (length(trim(category)) > 0),
  description text not null check (length(trim(description)) > 0),
  amount_cents integer not null check (amount_cents > 0),
  staff text not null,
  spent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id text primary key,
  actor text not null,
  action text not null,
  detail text not null,
  logged_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id text primary key default 'default',
  print_receipts boolean not null default true,
  sound_alerts boolean not null default true,
  require_served_before_cleaning boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.settings (id)
values ('default')
on conflict (id) do nothing;

insert into public.staff_accounts (id, name, username, password, role, status)
values ('USR-01', 'Admin User', 'admin', 'admin123', 'Admin', 'Active')
on conflict (id) do nothing;

create index if not exists staff_accounts_role_idx on public.staff_accounts(role);
create index if not exists staff_accounts_status_idx on public.staff_accounts(status);

create index if not exists tables_area_idx on public.tables(area);
create index if not exists tables_status_idx on public.tables(status);

create index if not exists table_sessions_table_id_idx on public.table_sessions(table_id);
create index if not exists table_sessions_closed_at_idx on public.table_sessions(closed_at);

create index if not exists menu_items_category_idx on public.menu_items(category);
create index if not exists menu_items_station_idx on public.menu_items(station);
create index if not exists menu_items_available_idx on public.menu_items(available);
create index if not exists menu_items_archived_idx on public.menu_items(archived);

create index if not exists orders_session_id_idx on public.orders(session_id);
create index if not exists orders_table_id_idx on public.orders(table_id);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_payment_status_idx on public.orders(payment_status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_paid_at_idx on public.orders(paid_at desc);

create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists order_items_menu_item_id_idx on public.order_items(menu_item_id);

create index if not exists payments_order_id_idx on public.payments(order_id);
create index if not exists payments_status_idx on public.payments(status);
create index if not exists payments_paid_at_idx on public.payments(paid_at desc);

create index if not exists expenses_category_idx on public.expenses(category);
create index if not exists expenses_spent_at_idx on public.expenses(spent_at desc);

create index if not exists audit_logs_actor_idx on public.audit_logs(actor);
create index if not exists audit_logs_logged_at_idx on public.audit_logs(logged_at desc);

drop trigger if exists set_staff_accounts_updated_at on public.staff_accounts;
create trigger set_staff_accounts_updated_at
before update on public.staff_accounts
for each row execute function public.set_updated_at();

drop trigger if exists set_tables_updated_at on public.tables;
create trigger set_tables_updated_at
before update on public.tables
for each row execute function public.set_updated_at();

drop trigger if exists set_table_sessions_updated_at on public.table_sessions;
create trigger set_table_sessions_updated_at
before update on public.table_sessions
for each row execute function public.set_updated_at();

drop trigger if exists set_menu_items_updated_at on public.menu_items;
create trigger set_menu_items_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists set_payments_updated_at on public.payments;
create trigger set_payments_updated_at
before update on public.payments
for each row execute function public.set_updated_at();

drop trigger if exists set_expenses_updated_at on public.expenses;
create trigger set_expenses_updated_at
before update on public.expenses
for each row execute function public.set_updated_at();

drop trigger if exists set_settings_updated_at on public.settings;
create trigger set_settings_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

-- Browser access for the current custom login prototype.
-- Replace this with Supabase Auth and role-based policies before production.
grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on
  public.staff_accounts,
  public.tables,
  public.table_sessions,
  public.menu_items,
  public.orders,
  public.order_items,
  public.payments,
  public.expenses,
  public.audit_logs,
  public.settings
to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

do $$
declare
  app_table text;
begin
  foreach app_table in array array[
    'staff_accounts',
    'tables',
    'table_sessions',
    'menu_items',
    'orders',
    'order_items',
    'payments',
    'expenses',
    'audit_logs',
    'settings'
  ]
  loop
    execute format('alter table public.%I enable row level security', app_table);
    execute format('drop policy if exists "Allow app CRUD" on public.%I', app_table);
    execute format(
      'create policy "Allow app CRUD" on public.%I for all to anon, authenticated using (true) with check (true)',
      app_table
    );
  end loop;
end $$;

commit;
